source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-activerecord'
gem 'activerecord', 'require' => 'active_record'
gem 'rake'
gem 'json'
gem 'pg'
gem 'bcrypt'
gem 'dotenv'
gem 'aws-sdk'
gem 'rack-cors', :require => 'rack/cors'

gem 'faker'
gem 'pry'